hl.bind("SUPER + Return", hl.dsp.exec_cmd("wezterm"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("flameshot gui"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("~/.config/wofi/power.sh"))
hl.bind("SUPER + P", hl.dsp.exec_cmd("~/.config/wofi/screen.sh"))
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

hl.bind("SUPER + SHIFT + Q", hl.dsp.window.close())
hl.bind("SUPER + E", hl.dsp.layout("togglesplit"))

hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }))

hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

hl.bind("SUPER + CONTROL + H", hl.dsp.focus({ workspace = "m-1" }))
hl.bind("SUPER + CONTROL + L", hl.dsp.focus({ workspace = "m+1" }))
hl.bind("SUPER + CONTROL + left", hl.dsp.focus({ workspace = "m-1" }))
hl.bind("SUPER + CONTROL + right", hl.dsp.focus({ workspace = "m+1" }))

hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + G", hl.dsp.group.toggle())
hl.bind("SUPER + TAB", hl.dsp.group.next())
hl.bind("SUPER + SHIFT + TAB", hl.dsp.group.prev())

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))

hl.bind("SUPER + CONTROL + 1", hl.dsp.window.move({ workspace = "1", follow = true }))
hl.bind("SUPER + CONTROL + 2", hl.dsp.window.move({ workspace = "2", follow = true }))
hl.bind("SUPER + CONTROL + 3", hl.dsp.window.move({ workspace = "3", follow = true }))
hl.bind("SUPER + CONTROL + 4", hl.dsp.window.move({ workspace = "4", follow = true }))
hl.bind("SUPER + CONTROL + 5", hl.dsp.window.move({ workspace = "5", follow = true }))
hl.bind("SUPER + CONTROL + 6", hl.dsp.window.move({ workspace = "6", follow = true }))
hl.bind("SUPER + CONTROL + 7", hl.dsp.window.move({ workspace = "7", follow = true }))
hl.bind("SUPER + CONTROL + 8", hl.dsp.window.move({ workspace = "8", follow = true }))
hl.bind("SUPER + CONTROL + 9", hl.dsp.window.move({ workspace = "9", follow = true }))
hl.bind("SUPER + CONTROL + 0", hl.dsp.window.move({ workspace = "10", follow = true }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1", follow = false }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2", follow = false }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3", follow = false }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4", follow = false }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5", follow = false }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6", follow = false }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7", follow = false }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8", follow = false }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9", follow = false }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10", follow = false }))

hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

hl.bind("code:232", hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true })
hl.bind("code:233", hl.dsp.exec_cmd("brightnessctl set +5%"), { repeating = true })
hl.bind("code:121", hl.dsp.exec_cmd("amixer -D pipewire sset Master toggle"), { repeating = true })
hl.bind("code:122", hl.dsp.exec_cmd('amixer -D pipewire sset Master "5%-"'), { repeating = true })
hl.bind("code:123", hl.dsp.exec_cmd('amixer -D pipewire sset Master "5%+"'), { repeating = true })
