hl.on("hyprland.start", function()
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
  hl.exec_cmd("wl-paste --type text  --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("dunst")
  hl.exec_cmd("ags run --gtk 4 2>&1 > /home/watasuke/ags.log")
  hl.exec_cmd("dex -a -s ~/.config/autostart")
end)
