# general
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ryanoasis/nerd-fonts'

## Git操作
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-surround'

## C-qでウィンドウをリサイズ
[[plugins]]
repo = 'simeji/winresizer'

## LSPによる補完など
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'


# Language
[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'rhysd/vim-clang-format'

[[plugins]]
repo = 'cespare/vim-toml'


# Looks
[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'vim-airline/vim-airline'

