[window]
dynamic_title = true

[window.padding]
x = 2
y = 2

[cursor.style]
shape = "Beam"

[font]
size = 10.0

[font.normal]
family = "MyricaM"

[scrolling]
history = 10000

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[colors.normal]
black   = "0x1e2127"
blue    = "0x61afef"
cyan    = "0x56b6c2"
green   = "0x98c379"
magenta = "0xc678dd"
red     = "0xe06c75"
white   = "0x828791"
yellow  = "0xd19a66"

[colors.bright]
black   = "0x5c6370"
blue    = "0x61afef"
cyan    = "0x56b6c2"
green   = "0x98c379"
magenta = "0xc678dd"
red     = "0xe06c75"
white   = "0xe6efff"
yellow  = "0xd19a66"

[colors.dim]
black   = "0x1e2127"
blue    = "0x61afef"
cyan    = "0x56b6c2"
green   = "0x98c379"
magenta = "0xc678dd"
red     = "0xe06c75"
white   = "0x828791"
yellow  = "0xd19a66"
